### PR TITLE
overhauled sounds for penetration, ricochet, explosion 

### PR DESCRIPTION
**Pull request by fnden**
-44 new sounds
-improved sounds for piercing, ricochet, and explosion 
-piercing and ricochet sounds based on caliber

### CODE REVIEW

**Comment by Stooberton** [comment]
Tried it out for just a minute or to when I had the time. Firstly, I really appreciate the effort.

Anyway, from the short time I experimented with it, two things stood out to me:
The explosion sounds seem to be overly **EPIC** on smaller calibers (I only played with it using a 30mm). It was out of place with the size of the explosion and was excessively long.
Metal ricochet sounds were played even when shooting the world, and if I remember correctly the volume seemed inappropriate and overall it was quite jarring.

**Comment by TwistedTail** [comment]
The idea is nice, having a wider variety of sound effects played when something happens makes it way less monotone than before. However, there's a few things I'd like to note about it.

In my opinion, both penetrations and ricochets are really quiet, even after getting by the side of the impact. Nothing than playing with the sound level a bit can't fix. [You could try this trick as well if you like.](https://twitter.com/Case_Portman/status/1172839179157475328)

The part @Stooberton mentioned about ricochets is merely ACF's fault; due to the fact effects only rely on the really limited amount of information you can give them, there was never an effort to be able to tell them what kind of surface was hit. It's a limitation that has been noted by other people working on effects too, so we'll eventually have to deal with it. If it were possible, adding some extra sounds for other types of surfaces would be helpful for the future.

Some of the sounds are perfect, I can't say anything about most of the medium penetration and ricochet sounds, but there's something I noticed with quite a few of them: They try to do a lot of things instead of just the one thing they should do, after all they're really short lived events that can happen multiple times in a short amount of time. As a side-note: I don't know if it would be possible to have an extra set of sounds for smaller calibers as well.

**Comment by fnden** [comment]
Thanks for the feedback from both of you! I agree on the explosions being a little overkill and are working on to get some new sounds that would fit its role. Ill add smaller caliber sounds and see if I can incorporate a way to detect world to give it more fitting sounds.

**Comment by Stooberton** [comment]
@fnden any updates on this?

**Pull request closed without merging**
