### PR TITLE
Lower decible of some sounds and add volume scale option

### PR DESCRIPTION
**Pull request by thegrb93**
Will need to test it

### CODE REVIEW

**Comment by PolySteam** [comment]
Angry linter strikes again

**Comment by thegrb93** [comment]
Haven't seen any problems.

**Comment by TwistedTail** [comment]
Most of these are controlling server-side produced sounds, intended?

**Comment by thegrb93** [comment]
I added the volume scaling to every produced sound, so yeah I guess. It'll be server controlled unfortunately, but if the sounds were clientside then it could be client controlled. I think this is fine for now.

**Pull request merged**
