### PR TITLE
Improved AIM-54

### PR DESCRIPTION
**Pull request by 2Sprocket**
Materials and model replaced with War Thunders models and materials. collision model was modified to fit the slightly different shape

### CODE REVIEW

**Comment by TwistedTail** [comment]
I never really noticed than this model was on the main addon. Could it be possible for you to make this change on the missiles repository instead? I'll deal with the model on this one.

**Comment by TwistedTail** [comment]
Also, just give it a different name (aim54a, for example) to still allow the old model to be used by people if they want to.

**Comment by 2Sprocket** [comment]
like add it to your repository?

**Comment by TwistedTail** [comment]
Yeah, it makes sense that missile content remains on the missile repository.

**Comment by 2Sprocket** [comment]
by the looks of it, it doesn't exist in TwistedTail/ACF-Missiles

**Comment by TwistedTail** [comment]
Yeah.

**Pull request closed without merging**
