### PR TITLE
Strenghtened, stabilized new brakes

### PR DESCRIPTION
**Pull request by Alexandre425**
Made brakes stronger and more consistent by multiplying the torque by the wheel inertia, and smoother by applying less brakes at lower velocities.

Shouldn't twitch anymore (at the cost of some slope braking) and should be sufficiently strong provided the wheels are heavy enough.

This should be tested with a proper vehicle though.

### CODE REVIEW

**Comment by TheLight91** [comment]
This fix doesn't fix the iossue. Brakes don't twitch at low speeds like before, but aren't stronger.

**Comment by Alexandre425** [comment]
> This fix doesn't fix the iossue. Brakes don't twitch at low speeds like before, but aren't stronger.

Can you provide me with a vehicle that demonstrates this? I can't replicate it

**Comment by TheLight91** [comment]
[test.txt](https://github.com/Stooberton/ACF-3/files/8188874/test.txt)

**Comment by TheLight91** [comment]
Can you show me the tank or whatever vehicle you use for your tests? Maybe there's something wrong in my codes or how I set up things.

**Comment by Alexandre425** [comment]
> Can you show me the tank or whatever vehicle you use for your tests? Maybe there's something wrong in my codes or how I set up things.

The issue I found with the tank you provided me is it has an extremely high physical mass. I would unweld the engine, transmission, and so on. Also, adding some mass to your drive wheel (or removing some from your road wheels) will help.

**Comment by TheLight91** [comment]
> > Can you show me the tank or whatever vehicle you use for your tests? Maybe there's something wrong in my codes or how I set up things.
> 
> The issue I found with the tank you provided me is it has an extremely high physical mass. I would unweld the engine, transmission, and so on. Also, adding some mass to your drive wheel (or removing some from your road wheels) will help.

It was never an issue with ACF2, besides if I don't have high phisical mass the gun will be floppy and move the whole tank around, it's a 203mm afterall. Or just I go the full cheese way and have all parented and fake?

**Comment by Alexandre425** [comment]
> > > Can you show me the tank or whatever vehicle you use for your tests? Maybe there's something wrong in my codes or how I set up things.
> > 
> > 
> > The issue I found with the tank you provided me is it has an extremely high physical mass. I would unweld the engine, transmission, and so on. Also, adding some mass to your drive wheel (or removing some from your road wheels) will help.
> 
> It was never an issue with ACF2, besides if I don't have high phisical mass the gun will be floppy and move the whole tank around, it's a 203mm afterall. Or just I go the full cheese way and have all parented and fake?

Cheese? It's the correct way of doing things, now that its allowed.

**Comment by TwistedTail** [comment]
> Or just I go the full cheese way and have all parented and fake?

As far as I'm aware, real vehicles don't wobble like crazy in all directions for the sole reason they have a turret attached to them. Rigidity is just one of the many reasons why parenting everything, including turrets, is the proper way to do things.

**Comment by TheLight91** [comment]
So instead of a real gun constrained to base, I just parent the gun to a gate and move the gate instead? No inertia of gun, no recoil, no weight balance issue of a gun too big for the tank?

**Comment by Alexandre425** [comment]
> So instead of a real gun constrained to base, I just parent the gun to a gate and move the gate instead? No inertia of gun, no recoil, no weight balance issue of a gun too big for the tank?

There is still recoil, and you parent it to a holo

**Pull request merged**
